### ISSUE TITLE
Debug: option to add a variable to the 'watch' tab does not appear at the start

### ISSUE THREAD

**Issue by ma-michelle** [cee-studio/IDE#11] opened 2020-07-28 06:47 UTC
Upon opening the debugger window, this is what the 'watch' tab looks like:

![image](https://user-images.githubusercontent.com/56993432/88628856-64d14f00-d063-11ea-8fce-e835b7c3212d.png)

The option to add a variable only appears after starting debug mode and then pressing 'stop'.

![image](https://user-images.githubusercontent.com/56993432/88629059-a7932700-d063-11ea-82cf-b07aac32dcc3.png)

**Comment by mlite** [comment] 2020-07-28 17:54
It's a bug.

**Comment by xzhang1863** [comment] 2020-08-02 23:30
The original design was that user is allowed to add watch variable only after debug session starts. 
The basic reason behind this is that we need to do 2 things when adding a watch variable according to gdb-mi:
- Create variable object
- Evaluate the variable object to get the value of the expression

All those gdb commands are accepted when debug session starts, so the simplified design only allows adding new watch expression after debugging starts.

It is possible to support adding watch expression before debugging starts, what we need to do is:
- Record the newly added watch expression in a pending list
- When debug session starts, send gdb commands to evaluate those watch expressions

Will this feature a mandatory requirement?

**Comment by ma-michelle** [comment] 2020-08-02 23:41
> The original design was that user is allowed to add watch variable only after debug session starts.
> The basic reason behind this is that we need to do 2 things when adding a watch variable according to gdb-mi:
> ...

So in our current implementation, watch variables can only be added while in debug mode, correct?
But they do not appear even after debug mode has started. Here's what I did:

1. open cee.studio in an incognito window (I think the project settings save due to browser cache, so bugs may not appear consistently)
2. do not open the debugger window at this point
3. click on debug mode, the debugger window should now automatically appear
4. there should not be an option to add a watch variable, as shown in the original post

If someone else could confirm this using these steps that would be great. I apologize if there was a miscommunication in the original post.

**Comment by mlite** [comment] 2020-08-03 23:07
It's a usability issue.  I can confirm the capability of being able to add a watched variable is not enabled reliably.   
From the usability's view point,  we should allow users to add a watched variable even if there is no debugging session,  otherwise we should mute the option until a debugging session is started.

**Comment by xzhang1863** [comment] 2020-08-04 03:14
Allowing user to add watch expression outside of an active debugging session may not be a good practice, because:
- Watch expression is associated with current debugging context, without which the watch expression won't make any sense
- Visual Studio C++ does not give user the option to show "Watch" debug window outside of a debug session

The acceptable solution can be that we hide those sections that are associated with debugging context, and only make them visible when debug session starts.

On the other hand, this does not seem to be a real usability issue. Our current debugger UI is still a very basic approach, it is worth a full re-design to make it more user-friendly.

**Comment by mlite** [comment] 2020-08-04 05:15
I think disabling the whole panel until a debugging session is a good solution for now.

**Comment by xzhang1863** [comment] 2020-08-06 06:14
2 issues here:
- Before gdb session starts, we don't allow adding watch variable
- The first time user clicks "Debug" button, "Watch" tab does not allow user to add expression.

The first issue is as-designed. One way to improve usability is to make watch-tab grayed out, so as to make it clear that it is not editable.

The second issue is a bug, I am able to reproduce it now. The fix has been submitted into x13 branch.

**Comment by mlite** [comment] 2020-08-06 20:01
the second issue is released to the staging and production site.  I will work on the first one

**Comment by xzhang1863** [comment] 2020-08-15 20:25
This issue should have been fixed, please verify.

**Closed** 2020-08-15 20:54 UTC
